# Generated by Django 5.0.6 on 2024-06-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
