# Generated by Django 5.0.6 on 2024-06-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0004_alter_venda_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
